spring.application.name=DJ

discord.token=${DISCORD_TOKEN}
discord.guild-id=${DISCORD_GUILD_ID}
discord.guild-id2=${DISCORD_GUILD_ID_TEST}

# H2 guardara los datos en un archivo llamado music_db en el directorio data
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/music_db

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# hablilitamos la consola web de H2 
spring.h2.console.path=/h2-console

# Configuracion de Hebernate JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

server.port=8080
