spring.application.name=DJ

# Discord
discord.token=${DISCORD_TOKEN}
discord.guild-id=${DISCORD_GUILD_ID}
discord.guild-id-test=${DISCORD_GUILD_ID_TEST}
youtube.refresh-token=$(YOUTUBE_REFRESH_TOKEN)

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/djbot}
spring.datasource.username=${DB_USER:djbot}
spring.datasource.password=${DB_PASSWORD:djbot}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080
